apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-metrics
  namespace: monitoring
  labels:
    app: scaletestapp
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: scaletestapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
